"""
Generate the Wazuh rule set from siem.py, so the two cannot drift.

WHY THIS EXISTS
---------------
siem.py assigns every finding a severity on Wazuh's 0-15 scale and the module
claimed that "alert thresholds work without per-event tuning". Black-box
checking showed that claim was unsupported: with `<log_format>json</log_format>`
Wazuh's built-in JSON decoder parses our fields into data.*, but **it does not
read our severity**. Wazuh's alert level comes from whichever RULE matches, and
no rule matched our events at all, so everything arrived at the manager's
default level for decoded JSON. The number we were so careful about meant
nothing on the receiving end.

This emits real rules that map each event to the intended Wazuh level, with its
MITRE technique and its kill-chain stage. Generated rather than hand-written so
adding an event to siem.EVENTS cannot silently leave the SIEM side behind --
tests/test_wazuh_rules.py fails if the checked-in XML is stale.

    python scripts/gen_wazuh_rules.py            # write the XML
    python scripts/gen_wazuh_rules.py --check    # verify it is current
"""
import argparse
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

import siem            # noqa: E402
import killchain       # noqa: E402

RULES_FILE = ROOT / "wazuh" / "rules" / "clienthoneypot_rules.xml"

# Local rule IDs. Wazuh reserves <100000 for its own rule set; 100000+ is the
# documented range for site-local rules.
BASE_ID = 100100

# NOTE: a double hyphen is illegal inside an XML comment, so the prose below
# uses commas where the rest of this codebase would use a dash. The generated
# file failed to parse until this was fixed.
HEADER = """<!--
  ClientHoneypot to Wazuh rules.

  GENERATED by scripts/gen_wazuh_rules.py from src/siem.py. Do not edit by
  hand: regenerate instead, or tests/test_console_auth_and_wazuh.py will fail.

  Install on the MANAGER:
      cp clienthoneypot_rules.xml /var/ossec/etc/rules/
      chown wazuh:wazuh /var/ossec/etc/rules/clienthoneypot_rules.xml
      /var/ossec/bin/wazuh-control restart

  The AGENT (on the host running the collector) needs the localfile block
  printed by the dashboard, i.e. siem.wazuh_agent_config().

  Levels mirror src/siem.py EVENTS. Wazuh's own rule level is what drives
  alerting and thresholds; the JSON "event.severity" field we ship is data,
  not a level, which is precisely why these rules have to exist.
-->
<group name="clienthoneypot,honeypot,deception,">
"""

FOOTER = "</group>\n"

PARENT = """
  <!-- Parent: every finding this platform ships. Level 0 = do not alert on the
       parent itself; the child rules below carry the real levels. -->
  <rule id="{rid}" level="0">
    <decoded_as>json</decoded_as>
    <field name="vendor">^ClientHoneypot$</field>
    <description>ClientHoneypot finding</description>
  </rule>
"""


def rule_xml(rid: int, parent: int, action: str, level: int,
             description: str) -> str:
    technique = siem.TECHNIQUE.get(action)
    stage = killchain.stage_for(action)

    bits = [f'  <rule id="{rid}" level="{level}">',
            f'    <if_sid>{parent}</if_sid>',
            f'    <field name="event.action">^{escape(action)}$</field>',
            f'    <description>ClientHoneypot: {escape(description)}</description>']
    if stage:
        # Searchable in the manager UI, so an analyst can pivot on "who reached
        # installation" without knowing our event vocabulary.
        bits.append(f'    <group>killchain_{stage},</group>')
    if technique:
        bits.append('    <mitre>')
        bits.append(f'      <id>{technique}</id>')
        bits.append('    </mitre>')
    bits.append('  </rule>')
    return "\n".join(bits) + "\n"


def generate() -> str:
    out = [HEADER, PARENT.format(rid=BASE_ID)]
    # Sorted by descending severity so the most serious rules read first.
    events = sorted(siem.EVENTS.items(), key=lambda kv: (-kv[1][0], kv[0]))
    for offset, (action, (level, description)) in enumerate(events, start=1):
        out.append("\n")
        out.append(rule_xml(BASE_ID + offset, BASE_ID, action, level, description))
    out.append(FOOTER)
    return "".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the checked-in file is stale")
    args = ap.parse_args(argv)

    wanted = generate()
    if args.check:
        current = RULES_FILE.read_text(encoding="utf-8") if RULES_FILE.exists() else ""
        if current != wanted:
            print("wazuh rules are STALE — run: python scripts/gen_wazuh_rules.py")
            return 1
        print(f"wazuh rules current ({len(siem.EVENTS)} events)")
        return 0

    RULES_FILE.parent.mkdir(parents=True, exist_ok=True)
    RULES_FILE.write_text(wanted, encoding="utf-8")
    print(f"wrote {RULES_FILE} — {len(siem.EVENTS)} rules "
          f"(ids {BASE_ID + 1}..{BASE_ID + len(siem.EVENTS)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
